
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GameUnlock : Luban.BeanBase
{
    public GameUnlock(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Show"].IsNumber) { throw new SerializationException(); }  Show = _buf["Show"]; }
        { if(!_buf["Unlock"].IsNumber) { throw new SerializationException(); }  Unlock = _buf["Unlock"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Desc"].IsString) { throw new SerializationException(); }  Desc = _buf["Desc"]; }
    }

    public static GameUnlock DeserializeGameUnlock(JSONNode _buf)
    {
        return new GameUnlock(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 显示条件
    /// </summary>
    public readonly int Show;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly int Unlock;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -1622231562;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Type:" + Type + ","
        + "Show:" + Show + ","
        + "Unlock:" + Unlock + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "}";
    }
}

}

