
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GuideLevel : Luban.BeanBase
{
    public GuideLevel(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Row"].IsNumber) { throw new SerializationException(); }  Row = _buf["Row"]; }
        { if(!_buf["Column"].IsNumber) { throw new SerializationException(); }  Column = _buf["Column"]; }
        { if(!_buf["Ball"].IsString) { throw new SerializationException(); }  Ball = _buf["Ball"]; }
    }

    public static GuideLevel DeserializeGuideLevel(JSONNode _buf)
    {
        return new GuideLevel(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 行
    /// </summary>
    public readonly int Row;
    /// <summary>
    /// 列
    /// </summary>
    public readonly int Column;
    /// <summary>
    /// 小球信息
    /// </summary>
    public readonly string Ball;
   
    public const int __ID__ = 2041039368;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Row:" + Row + ","
        + "Column:" + Column + ","
        + "Ball:" + Ball + ","
        + "}";
    }
}

}

