
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Level : Luban.BeanBase
{
    public Level(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["LevelId"].IsNumber) { throw new SerializationException(); }  LevelId = _buf["LevelId"]; }
        { if(!_buf["BrickId"].IsNumber) { throw new SerializationException(); }  BrickId = _buf["BrickId"]; }
        { if(!_buf["Row"].IsNumber) { throw new SerializationException(); }  Row = _buf["Row"]; }
        { if(!_buf["Column"].IsNumber) { throw new SerializationException(); }  Column = _buf["Column"]; }
        { if(!_buf["BrickType"].IsString) { throw new SerializationException(); }  BrickType = _buf["BrickType"]; }
        { if(!_buf["BrickContainer"].IsString) { throw new SerializationException(); }  BrickContainer = _buf["BrickContainer"]; }
        { if(!_buf["BrickHp"].IsNumber) { throw new SerializationException(); }  BrickHp = _buf["BrickHp"]; }
        { if(!_buf["BombCountDown"].IsNumber) { throw new SerializationException(); }  BombCountDown = _buf["BombCountDown"]; }
        { if(!_buf["SpawnGroup"].IsNumber) { throw new SerializationException(); }  SpawnGroup = _buf["SpawnGroup"]; }
    }

    public static Level DeserializeLevel(JSONNode _buf)
    {
        return new Level(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 砖块id
    /// </summary>
    public readonly int BrickId;
    /// <summary>
    /// 行
    /// </summary>
    public readonly int Row;
    /// <summary>
    /// 列
    /// </summary>
    public readonly int Column;
    /// <summary>
    /// 砖块类型
    /// </summary>
    public readonly string BrickType;
    /// <summary>
    /// 砖块颜色
    /// </summary>
    public readonly string BrickContainer;
    /// <summary>
    /// 砖块HP
    /// </summary>
    public readonly int BrickHp;
    /// <summary>
    /// 炸弹倒计时
    /// </summary>
    public readonly int BombCountDown;
    /// <summary>
    /// 生成组
    /// </summary>
    public readonly int SpawnGroup;
   
    public const int __ID__ = 73313124;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "LevelId:" + LevelId + ","
        + "BrickId:" + BrickId + ","
        + "Row:" + Row + ","
        + "Column:" + Column + ","
        + "BrickType:" + BrickType + ","
        + "BrickContainer:" + BrickContainer + ","
        + "BrickHp:" + BrickHp + ","
        + "BombCountDown:" + BombCountDown + ","
        + "SpawnGroup:" + SpawnGroup + ","
        + "}";
    }
}

}

