
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbGuideLevel TbGuideLevel {get; }
    public TbLevel TbLevel {get; }
    public TbLanguage TbLanguage {get; }
    public TbLevelConfig TbLevelConfig {get; }
    public TbKV TbKV {get; }
    public TbGameUnlock TbGameUnlock {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGuideLevel = new TbGuideLevel(loader("tbguidelevel"));
        TbLevel = new TbLevel(loader("tblevel"));
        TbLanguage = new TbLanguage(loader("tblanguage"));
        TbLevelConfig = new TbLevelConfig(loader("tblevelconfig"));
        TbKV = new TbKV(loader("tbkv"));
        TbGameUnlock = new TbGameUnlock(loader("tbgameunlock"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGuideLevel.ResolveRef(this);
        TbLevel.ResolveRef(this);
        TbLanguage.ResolveRef(this);
        TbLevelConfig.ResolveRef(this);
        TbKV.ResolveRef(this);
        TbGameUnlock.ResolveRef(this);
    }
}

}
