
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbGameUnlock
{
    private readonly System.Collections.Generic.Dictionary<int, GameUnlock> _dataMap;
    private readonly System.Collections.Generic.List<GameUnlock> _dataList;
    
    public TbGameUnlock(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GameUnlock>();
        _dataList = new System.Collections.Generic.List<GameUnlock>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GameUnlock _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = GameUnlock.DeserializeGameUnlock(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GameUnlock> DataMap => _dataMap;
    public System.Collections.Generic.List<GameUnlock> DataList => _dataList;

    public GameUnlock GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GameUnlock Get(int key) => _dataMap[key];
    public GameUnlock this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

