
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbGuideLevel
{
    private readonly System.Collections.Generic.Dictionary<int, GuideLevel> _dataMap;
    private readonly System.Collections.Generic.List<GuideLevel> _dataList;
    
    public TbGuideLevel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GuideLevel>();
        _dataList = new System.Collections.Generic.List<GuideLevel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            GuideLevel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = GuideLevel.DeserializeGuideLevel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GuideLevel> DataMap => _dataMap;
    public System.Collections.Generic.List<GuideLevel> DataList => _dataList;

    public GuideLevel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GuideLevel Get(int key) => _dataMap[key];
    public GuideLevel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

