
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbKV
{
    private readonly System.Collections.Generic.Dictionary<string, KV> _dataMap;
    private readonly System.Collections.Generic.List<KV> _dataList;
    
    public TbKV(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, KV>();
        _dataList = new System.Collections.Generic.List<KV>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            KV _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = KV.DeserializeKV(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, KV> DataMap => _dataMap;
    public System.Collections.Generic.List<KV> DataList => _dataList;

    public KV GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public KV Get(string key) => _dataMap[key];
    public KV this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

