
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbLevelConfig
{
    private readonly System.Collections.Generic.Dictionary<int, LevelConfig> _dataMap;
    private readonly System.Collections.Generic.List<LevelConfig> _dataList;
    
    public TbLevelConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelConfig>();
        _dataList = new System.Collections.Generic.List<LevelConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LevelConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LevelConfig.DeserializeLevelConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LevelConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelConfig> DataList => _dataList;

    public LevelConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LevelConfig Get(int key) => _dataMap[key];
    public LevelConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

